coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0%
        informational: false  # 关键：这会让 Codecov 报告失败状态，而不是仅仅发个信息
    patch:
      default:
        target: 90%
        informational: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false