name: E2E Visual Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Visual Report Comment
        id: generate_comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Hello");
            return "done";
